### ISSUE TITLE
あおい

### ISSUE THREAD

**Issue by kubo-aoi** [c0a21020/ProjExD#18]
https://github.com/c0a21020/ProjExD/blob/be9e1f7abcbd725fa6a3411b8c5c82be6f26b454/ex05/dodge_bomb.py#L104

ここら辺はそれぞれの初期座標かな？どうやって決めた？

**Comment by c0a21020** [comment]
初期座標ではなくて、x方向とy方向に今後どれくらい進むかをそれぞれバラバラになるようにしてる。
